"""
"""
import json, re, sys

LAB = re.compile(r'\[(entity|property):([^\]]*)\]')

# The prompt arms, in the order the thesis reports them.
ARMS = [("baseline",                   "outputs/linked_base-qwen.json"),
        ("idiom rules",                "outputs/linked_idiom-qwen.json"),
        ("schema evidence, verbose",   "outputs/linked_grounded.json"),
        ("schema evidence, targeted",  "outputs/linked_grounded-targeted.json"),
        ("construct profile",          "outputs/linked_profile.json"),
        ("constrained vocabulary",     "outputs/linked_constrained.json"),
        ("both (factorial)",           "outputs/linked_both.json")]

# Positive control: a run known to have been generated by the open model.
CONTROL = ("open-backbone (control)",
           "outputs/linked_queries_qwen-qwen2-5-14b-instruct_official.json")

CAMEL_LIMIT = 8   # a clean arm must stay at or below this


def fingerprint(path):
    d = json.load(open(path))
    u = sorted({m.group(2) for v in d.values()
                for m in LAB.finditer(v.get("labeled_query") or "")})
    camel = sum(1 for l in u if re.search(r'[a-z][A-Z]', l) and ' ' not in l)
    snake = sum(1 for l in u if '_' in l)
    bare  = sum(1 for l in u if re.fullmatch(r'[PQ]\d+', l))
    return d, set(u), camel, snake, bare


hdr = f"{'arm':28s} {'rows':>5s} {'unique labels':>14s} {'camelCase':>10s} {'snake_case':>11s} {'bare ID':>8s}"
print(hdr)
sets, marks = {}, {}
for name, f in ARMS:
    d, u, camel, snake, bare = fingerprint(f)
    sets[name] = u
    marks[name] = (camel, snake, bare)
    print(f"{name:28s} {len(d):5d} {len(u):14d} {camel:10d} {snake:11d} {bare:8d}")

print()
cd, cu, ccamel, csnake, cbare = fingerprint(CONTROL[1])
print(f"{CONTROL[0]:28s} {len(cd):5d} {len(cu):14d} {ccamel:10d} {csnake:11d} {cbare:8d}")

print("\nreference fingerprints from X7 (official split, unfindable labels):")
print("  Qwen2.5-14B  camelCase 78   snake_case 8   bare ID 5")
print("  frontier     camelCase  0   snake_case 0   bare ID 0")

base = sets["baseline"]
print("\nlabel-set overlap with the baseline arm (Jaccard):")
for n in list(sets)[1:]:
    print(f"  {n:28s} {len(base & sets[n]) / len(base | sets[n]):.3f}")

# ---- verdict, computed rather than asserted -------------------------------
dirty = [n for n, (c, s, b) in marks.items() if c > CAMEL_LIMIT or s > 0]
control_dirty = ccamel > CAMEL_LIMIT or csnake > 0

print("\nVERDICT")
if control_dirty:
    print(f"  Positive control behaves as required: the open-backbone run shows "
          f"{ccamel} camelCase and {csnake} snake_case labels, so the fingerprint\n"
          f"  does discriminate and a clean result below is informative.")
else:
    print("  POSITIVE CONTROL FAILED: the open-backbone run does not show the open\n"
          "  model's signature, so this test cannot discriminate. Do not quote it.")
    sys.exit(1)

if dirty:
    print(f"  DRIFT DETECTED in: {', '.join(dirty)}. The affected\n"
          f"  comparisons are confounded by a change of generator.")
    sys.exit(1)

print(f"  All {len(ARMS)} arms carry the frontier fingerprint: at most {max(c for c,_,_ in marks.values())} "
      f"camelCase labels,\n  no snake_case, a handful of bare identifiers. None shows the open model's\n"
      f"  signature, so the seven-arm comparison is not confounded by a change of\n"
      f"  generator.")
print("""  The grounded arms nevertheless share only ~38% of their label vocabulary with
  the baseline, against 73% for the idiom arm: grounding triggers
  near-wholesale rewriting rather than targeted correction.

CAUTION FOR ANYONE RE-ANALYSING
  `data/pool_grounded.json` (2,417 entries) is a UNION pool spanning several runs,
  not the grounded arm's own candidate pool: its unfindable labels carry the
  open model's fingerprint (78 camelCase, 8 snake_case) because it also contains
  labels from the open-backbone official-split run. Do not use it to
  characterise the frontier model; use `data/batch_candidates.json`.""")
